(* Atoms *)
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;

digit_no_zero = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
digit = "0" | digit_no_zero ;

symbol = "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">"
       | "'" | '"' | "=" | "|" | "." | "," | ";" ;
symbol_id = "$" | "'" | "_";

character = letter | digit | symbol | "_" ;
id = ( specials_id | letter ), { specials_id | letter | digit };
integer = "0" | ( digit_no_zero, { digit } );

(* Expressions *)
expression = term | expression '+' term | expression '-' term;
term = factor | term '*' factor | term '/' factor | term '%' factor;
factor = primary | '-' factor | '+' factor;
primary = id | integer | '(' expression ')';